# Generated by Django 2.2.6 on 2019-11-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
